---
apiVersion: batch/v1
kind: Job
metadata:
  name: exchange-migrate
  namespace: exchange
  labels:
    app: exchange
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: exchange
        job: migrate
    spec:
      restartPolicy: Never
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
      containers:
        - name: migrate
          image: __IMAGE__
          imagePullPolicy: IfNotPresent
          env:
            - name: DEBUG
              value: "0"
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: exchange-db
                  key: host
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: exchange-db
                  key: port
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: exchange-db
                  key: name
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: exchange-db
                  key: user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: exchange-db
                  key: password
          command: ["/bin/sh","-c"]
          args:
            - |
              echo "Running migrations...";
              python manage.py migrate --noinput || exit 1;
              echo "Collecting static files...";
              python manage.py collectstatic --noinput || exit 1;
              echo "Done.";
